version: "3.3"

services:
  nginx:
    image: nginx
    container_name: nginx
    restart: always
    ports:
      - 80:80
    volumes:
      - ./nginx/config/nginx.conf:/etc/nginx/nginx.conf

  tomcat1:
    image: tomcat
    container_name: tomcat1
    ports:
      - 10001:8080
    volumes:
      - ./tomcat1/webapps/:/usr/local/tomcat/webapps/ROOT

  tomcat2:
    image: tomcat
    container_name: tomcat2
    ports:
      - 10002:8080
    volumes:
      - ./tomcat2/webapps/:/usr/local/tomcat/webapps/ROOT
