version: "3.3"

services:
  nginx:
    image: nginx
    container_name: nginx
    restart: always
    ports:
      - 80:80
      - 1111:8080
      - 9999:8081
    volumes:
      - ./nginx/config/nginx.conf:/etc/nginx/nginx.conf

  tomcat1:
    image: tomcat
    container_name: tomcat1
    volumes:
      - ./tomcat1/webapps/:/usr/local/tomcat/webapps/ROOT

  tomcat2:
    image: tomcat
    container_name: tomcat2
    volumes:
      - ./tomcat2/webapps/:/usr/local/tomcat/webapps/ROOT
